### ISSUE TITLE
[CHAT] 채팅방 화면 구성

### ISSUE THREAD

**Issue by ykc0131** [One-Trillion-Club/HUMATE-Android#28]
## 🍀 Description
채팅방 화면 UI 구성

## ✅ Todo
- [x] 채팅방 화면 UI 
- [x] #46
- [x] 채팅방 메이트 맺기 버튼 UI
- [x] 채팅방 전송 버튼 UI

## ETC
기타사항
