### ISSUE TITLE
[MEMBER] 로그인, 로그아웃 상태 저장/확인

### ISSUE THREAD

**Issue by choyeongwook** [One-Trillion-Club/HUMATE-Android#45]
## 🍀 Description
로그인 상태 저장 및 그에 따른 액티비티 전환 구현

## ✅ Todo
- [x] SharedPreferences를 사용한 로그인 상태 저장
- [x] 로그인 및 로그아웃 시  상태 변경
- [x] 앱이 시작될 때 이를 읽어 로그인 상태 확인 및 그에 따른 액티비티 전환

## ETC
