### ISSUE TITLE
[CHAT] 채팅방 UI 마무리

### ISSUE THREAD

**Issue by ykc0131** [One-Trillion-Club/HUMATE-Android#74]
## 🍀 Description
채팅방 UI 마무리 작업

## ✅ Todo
- [x] toolbar 작업
- [x] 공지글 작업
- [x] 채팅방 상단에 존재하는 매칭글 정보 
- [x] 메이트 버튼 클릭한 숫자
- [x] 날짜 예쁘게 처리
- [x] 유저 프로필 사진 넣기
- [x] tabLayout으로 전환
- [x] #81
