### ISSUE TITLE
[CHAT] 메이트 채팅방 활성화 (맺기 버튼, 다이얼)

### ISSUE THREAD

**Issue by ykc0131** [One-Trillion-Club/HUMATE-Android#85]
## 🍀 Description
메이트 맺기 버튼 활성화 및 다이얼, 메이트 채팅방으로 이동

## ✅ Todo
- [x] 메이트 맺기 버튼 
- [x] 메이트 버튼 활성화
- [x] 메이트 채팅방으로 이동
- [ ] 채팅방에서 활동으로 이동하는 버튼 활성화
