### ISSUE TITLE
[MEMBER] 영어 버전 및 NAV 수정

### ISSUE THREAD

**Issue by choyeongwook** [One-Trillion-Club/HUMATE-Android#89]
## 🍀 Description
회원 페이지 영어 버전 추가, NAV 수정

## ✅ Todo
- [x] member 페이지 영어 버전 추가
- [x] auth 페이지 영어 버전 추가
- [x] 마이페이지 메인에서 더 깊게 들어가면 NAV바 안보이게 수정
